### PR TITLE
I#40 documentation convertion to reStructuredText

### LINKED ISSUE #40: Documentation: Convert Markdown docs to reStructuredText
As a developer
Given I have project docs
And docs are written simple format using Markdown
When I want to follow project docs guideline
Then I need to rewrite them using reStructuredText

## History
According to project documentation guideline, project docs should be written using reStructured. But due to quick kickoff project, all of them were written using in Markdown. need to be converted to reStructuredText

## Task
- Convert documents of `docs` directory to reStructured
- Change the `.gihub/workflows/deploy-docs.yml` to build and deploy reST docs to static site
- Command to build on local environment as HTML and PDF for checking output

### PR DESCRIPTION
**Pull request by melon-ruet**
Fixes #40 

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [x] Improvement
- [ ] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
Convert docs from Markdown to reStructuredText
Docs deployment pipeline update to support  reStructuredText

## How to test

- [ ] Needs regression testing (add QA needed label)
- [x] After merging check the documentation site manually

## Checklist

- [x] I have tested these changes locally and they function as expected.
- [x] I have added or updated necessary documentation to reflect the changes.
- [x] I have followed the project's coding style and guidelines.
- [ ] I have added appropriate test coverage to ensure the changes are functioning correctly.
- [x] I have checked for any potential conflicts with other branches or pull requests.
- [ ] I have updated necessary OpenAPI specs

## Reviewer Request (optional)
Please check grammatical mistakes and missing docs that need to be converted to reST

## Screenshots (optional)
N/A

## Demo Link (optional)
Demo created from another branch other than master
https://craftsmenltd.github.io/BloodConnect/

## Known Issues (optional)
N/A

## Additional Notes (optional)
N/A

## Deploy risk & follow up

- [x] No risk
- [ ] Low
- [ ] High

### CODE REVIEW

**Comment by tohidrupok** [comment]
I can try to understand this Branch.

**Comment by shuaibq3** [comment]
> I can try to understand this Branch.

Yes, please share comments if you have

**Review by shuaibq3 — COMMENTED** [review]
Looks good. But I feel the whole docs build and deployment section has become too cumbersome. A lot is going on, with `make` files, `bat` file, `conf.py`, `dot` file (no idea why that would be necessary, maybe something to do with the build process of the tool used to convert restructured to html) to patch up image from a local folder (?).
I am sure everything done has been carefully evaluated and implemented. And the documentation site looks _richer_ now. A bit concerned about having introduced too much complexity in the process. If you feel that this is a worthy tradeoff please comment, we can get it approved and merged.
A small comment added. Please keep that into consideration as well, of course if you agree :)

**Comment by melon-ruet** [comment]
> Looks good. But I feel the whole docs build and deployment section has become too cumbersome. A lot is going on, with `make` files, `bat` file, `conf.py`, `dot` file (no idea why that would be necessary, maybe something to do with the build process of the tool used to convert restructured to html) to patch up image from a local folder (?). I am sure everything done has been carefully evaluated and implemented. And the documentation site looks _richer_ now. A bit concerned about having introduced too much complexity in the process. If you feel that this is a worthy tradeoff please comment, we can get it approved and merged. A small comment added. Please keep that into consideration as well, of course if you agree :)

docs/Makefile, bat and conf.py files are the part of sphinx. Among them docs/Makefile and bat are same, just they are used by Unix like system and Windows system respectively. conf.py is the config of sphinx. 

About project level Makefile, today or tomorrow we will need. And the code of that file only contains how to test docs locally. It is not too necessary but nice to have. Docker is being used here to avoid installation of python and the orther libs that are necessary for sphinx to local environment.

So there is only one thing left, how the windows users will test building docs locally. Currently Makefile contains only docker command, so it should work on windows. But how about `make` command. There are few windows specific solution for that. Do we want to add a "Howto windows section"?

**Comment by shuaibq3** [comment]
>Do we want to add a "Howto windows section"?

if necessary, of course we can add that. if not necessary now, and may be needed later, we can keep that ticket in the backlog until that is necessary.

About all the files involved in the process, from maintenance perspective, if they are a one time thing and will not need any change is future, then no issues. But if they need extending in future, it may be a good idea to reconsider the tradeoff here. And having completed this workflow, you are the right person to assess that. After all, this obviously has made the doc site richer than it was, so it clearly has a value.

How would you like to proceed?

**Comment by melon-ruet** [comment]
> > Do we want to add a "Howto windows section"?
> 
> if necessary, of course we can add that. if not necessary now, and may be needed later, we can keep that ticket in the backlog until that is necessary.

Not necessary right now but I kept the file so that in future we can test/fix it for windows and add necessary information in a doc

> About all the files involved in the process, from maintenance perspective, if they are a one time thing and will not need any change is future, then no issues. But if they need extending in future, it may be a good idea to reconsider the tradeoff here. And having completed this workflow, you are the right person to assess that. After all, this obviously has made the doc site richer than it was, so it clearly has a value.

They are one time. But need to be changed if the theme need to be updated, adding extension etc.

**Review by shuaibq3 — APPROVED** [review]
in that case no more feedback from my side.. changing the theme is a rare thing, once or twice every year, that even if we roam around the doc pages frequently and feel bored with the layout, which i doubt will happen :P
lets get it merged then! :D

**Pull request merged**
